# Kubernetes Secrets Template
# DO NOT commit secrets with actual values to version control
# Use external secret management tools (HashiCorp Vault, External Secrets Operator, etc.)

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: expense-tracker
  labels:
    app: expense-tracker
    component: database
type: Opaque
data:
  # Base64 encoded values - replace with actual secrets
  username: YWRtaW4=  # 'admin' in base64
  password: U2VjdXJlUGFzc3dvcmQxMjMh  # 'SecurePassword123!' in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: expense-tracker
  labels:
    app: expense-tracker
    component: backend
type: Opaque
data:
  # Base64 encoded values - replace with actual secrets
  mongo-uri: bW9uZ29kYjovL2FkbWluOlNlY3VyZVBhc3N3b3JkMTIzIUBtb25nb2RiLXNlcnZpY2U6MjcwMTcvZXhwZW5zZXRyYWNrZXI/YXV0aFNvdXJjZT1hZG1pbg==
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1mb3ItZXhwZW5zZS10cmFja2VyLWNoYW5nZS1pbi1wcm9kdWN0aW9uLW1ha2UtaXQtYXQtbGVhc3QtMzItY2hhcmFjdGVycw==
---
# Sealed Secret Example (for use with Sealed Secrets Controller)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-sealed-secret
  namespace: expense-tracker
  labels:
    app: expense-tracker
    component: database
spec:
  encryptedData:
    username: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...  # Encrypted by kubeseal
    password: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...  # Encrypted by kubeseal
  template:
    metadata:
      name: mongodb-secret
      namespace: expense-tracker
    type: Opaque
---
# External Secret Example (for use with External Secrets Operator)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-backend-secret
  namespace: expense-tracker
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
  - secretKey: mongo-uri
    remoteRef:
      key: secret/expense-tracker
      property: mongo-uri
  - secretKey: jwt-secret
    remoteRef:
      key: secret/expense-tracker
      property: jwt-secret 