apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: trackify-streamlined
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
  namespace: trackify-streamlined
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.15.4
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "myroot"
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8200"
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - vault
            - status
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - vault
            - status
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: trackify-streamlined
  labels:
    app: vault
spec:
  type: NodePort
  ports:
  - port: 8200
    targetPort: 8200
    nodePort: 30200
  selector:
    app: vault 